version: '3'

services:
  nginx:
    image: simaoneto/learn-docker-nginx
    ports:
      - "8000:80"
    volumes:
      - ./html:/usr/share/nginx/html
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "fullcycle"
    volumes:
      - ./mysql_data:/var/lib/mysql